import type { Metadata } from "next";
import "./globals.css";
import { MobileMenu } from "@/features/menu/components/mobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <MobileMenu />
      </body>
      {/* MobileMenu, DesktopMenu を useIsSmallDevice で切り替える */}
    </html>
  );
}
